import type { ThemePack } from "./types";
import { MONSTROS_PALETTE } from "./shared";

export const monstrosTheme: ThemePack = {
  schemaVersion: 1,
  id: "monstros",
  status: "published",
  name: "Lobisomem por Uma Noite — Monstros",
  shortName: "Monstros",
  locale: "pt-BR",
  brand: {
    title: "Lobisomem por Uma Noite — Monstros",
    eyebrow: "LOBISOMEM",
    subtitle: "POR UMA NOITE",
    name: "MONSTROS",
    tagline: "3 a 7 jogadores · uma noite · um monstro entre vocês",
    description: "Jogo multiplayer online de dedução social. Descubra quem é o monstro entre vocês!",
    logoSrc: "/art/logo.png",
    cardBackSrc: "/art/card-back.png",
    shareText: "Vem jogar Lobisomem por Uma Noite — Monstros!\nSala {code}: {url}",
  },
  terminology: {
    center: "Cemitério",
    centerPositionNames: ["esquerda", "meio", "direita"],
    village: "vila",
    wolfPack: "alcateia",
  },
  roles: {
    aldeao: {
      name: "Aldeão", letter: "A",
      description: "Não faz nada durante a noite. Use sua lábia para descobrir quem é o lobisomem.",
      nightHint: "Você dorme profundamente. Aguarde o amanhecer.",
      artSrc: "/art/aldeao.png", artAlt: "Aldeão de roupa verde",
    },
    lavrador: {
      name: "Aldeão", letter: "A",
      description: "Não faz nada durante a noite. A roupa preta e o arado distinguem este aldeão do de roupa verde.",
      nightHint: "Você dorme profundamente. Aguarde o amanhecer.",
      artSrc: "/art/lavrador.png", artAlt: "Aldeão de roupa preta com arado",
    },
    cacador: {
      name: "Caçador", letter: "C",
      description: "Esconde uma carta do centro sem olhar. Se for lobisomem, isso ajuda os aliados depois da votação, salvo se o Caçador for executado.",
      nightHint: "Escolha uma carta do Cemitério para esconder — você não pode olhar!",
      artSrc: "/art/cacador.png", artAlt: "Caçador",
    },
    bruxa: {
      name: "Bruxa", letter: "B",
      description: "Olha a carta de um jogador e vê os versos no Cemitério; um espaço vazio denuncia uma carta removida.",
      nightHint: "Espie um jogador. Observe também o Cemitério.",
      artSrc: "/art/bruxa.png", artAlt: "Bruxa",
    },
    lobisomem: {
      name: "Lobisomem", letter: "L",
      description: "Reconhece a alcateia e olha o Cemitério apenas no seu turno. Com dois jogadores lobisomens, a alcateia conversa em privado.",
      nightHint: "Veja a alcateia e o Cemitério. Memorizem e combinem o plano.",
      artSrc: "/art/lobisomem.png", artAlt: "Lobisomem",
    },
    mumia: {
      name: "Múmia", letter: "M",
      description: "Morto-vivo. Não age à noite e vence se for executado.",
      nightHint: "Você descansa em seu sarcófago. Aguarde o amanhecer.",
      artSrc: "/art/mumia.png", artAlt: "Múmia",
    },
    esqueleto: {
      name: "Esqueleto", letter: "E",
      description: "Morto-vivo. Não age à noite e vence se for executado.",
      nightHint: "Seus ossos descansam. Aguarde o amanhecer.",
      artSrc: "/art/esqueleto.png", artAlt: "Esqueleto",
    },
    zumbi: {
      name: "Zumbi", letter: "Z",
      description: "Remove uma carta do centro, assume o papel e executa sua ação. O Zumbi só vence como o papel assumido.",
      nightHint: "Escolha uma carta do Cemitério para devorar e assumir.",
      artSrc: "/art/zumbi.png", artAlt: "Zumbi",
    },
    vampiro: {
      name: "Vampiro", letter: "V",
      description: "Troca sua carta com a de outro jogador ou com uma do Cemitério, em segredo.",
      nightHint: "Escolha um jogador ou uma carta do Cemitério para trocar.",
      artSrc: "/art/vampiro.png", artAlt: "Vampiro",
    },
  },
  teams: {
    aliados: { name: "Aliados", goal: "Descubram e eliminem um lobisomem.", winBlurb: "A vila encontrou a criatura." },
    lobisomens: { name: "Lobisomens", goal: "Sobrevivam e desviem o voto.", winBlurb: "A alcateia sobreviveu à noite." },
    "mortos-vivos": { name: "Mortos-Vivos", goal: "Façam a vila executar uma múmia ou um esqueleto.", winBlurb: "O ritual alimentou os mortos-vivos." },
    zumbi: { name: "Zumbi", goal: "Assuma outro papel; o Zumbi não vence sozinho.", winBlurb: "O destino foi roubado." },
  },
  rulesCopy: {
    deckSummary: "Baralho oficial: com 3, um lobisomem e múmia ou esqueleto; com 4–5, dois lobisomens; a partir de 5 entram os dois mortos-vivos.",
    intro: "Cada pessoa recebe uma carta secreta e três ficam no Cemitério.",
    voting: "Ao amanhecer, discutam e votem. A carta escondida pelo Caçador só aparece no resultado.",
    winPriority: "Mortos-vivos vencem se um deles for executado. Aliados vencem se um lobisomem morrer ou pela condição do Caçador. Caso contrário, vencem os lobisomens.",
  },
  narration: {
    audioSrc: "/audio/monster.m4a",
    captionsSrc: "/audio/monster.vtt",
    ttsLocale: "pt-BR",
    segments: {
      intro: { narration: "Em uma cidade atormentada por criaturas da noite, anoiteceu." },
      cacador: { narration: "Acorde, caçador, comece sua caça.", actorPrompt: "Escolha uma carta do Cemitério para esconder — você não olha!" },
      bruxa: { narration: "Acorde, bruxa, preveja o futuro de alguém.", actorPrompt: "Espie um jogador e observe os versos no Cemitério." },
      lobisomem: { narration: "Acorde, lobisomem, forme sua alcateia.", actorPrompt: "Veja seus companheiros e as cartas no Cemitério." },
      zumbi: { narration: "Zumbi, levante e escolha o corpo do cemitério.", actorPrompt: "Escolha uma carta do Cemitério para assumir e faça a ação dela." },
      vampiro: { narration: "Acorde, vampiro, suga o sangue de uma vítima.", actorPrompt: "Escolha uma carta ou um jogador para trocar." },
      amanhecer: { narration: "Senhoras e senhores, amanheceu." },
    },
    subtitles: [
      { start: 0, end: 6.52, text: "Em uma cidade atormentada por criaturas da noite, anoiteceu." },
      { start: 10.54, end: 13.84, text: "Acorde, caçador, comece sua caça." },
      { start: 16, end: 26.16, text: "Um, dois, três, quatro, cinco, seis, sete, oito, nove, dez." },
      { start: 26.16, end: 30.64, text: "Acorde, bruxa, preveja o futuro de alguém." },
      { start: 32.56, end: 43.08, text: "Um, dois, três, quatro, cinco, seis, sete, oito, nove, dez." },
      { start: 43.94, end: 47.52, text: "Acorde, lobisomem, forme sua alcateia." },
      { start: 48.52, end: 59.36, text: "Um, dois, três, quatro, cinco, seis, sete, oito, nove, dez." },
      { start: 60.34, end: 63.7, text: "Zumbi, levante e escolha o corpo do cemitério." },
      { start: 65.52, end: 76.06, text: "Um, dois, três, quatro, cinco, seis, sete, oito, nove, dez." },
      { start: 76.06, end: 80, text: "Acorde, vampiro, suga o sangue de uma vítima." },
      { start: 81.06, end: 91.02, text: "Um, dois, três, quatro, cinco, seis, sete, oito, nove, dez." },
      { start: 92.2, end: 95.76, text: "Senhoras e senhores, amanheceu." },
    ],
  },
  ambient: { audioSrc: "/audio/background.mp3", volume: 0.18 },
  palette: MONSTROS_PALETTE,
};
