import type { ThemePack } from "./types";
import { buildNarrationSubtitles } from "./shared";

const lines = {
  intro: "A cidade dormiu, mas o Arquivo continuou trocando de mãos.",
  cacador: "Olheiro, acorde e esconda uma pasta sem ler a capa.",
  bruxa: "Tia do Zap, acorde e encaminhe a verdade de uma pessoa.",
  lobisomem: "Miliciano, acorde e reconheça quem controla o mesmo pedaço.",
  zumbi: "Laranja, acorde e assuma a ficha que sobrou no Arquivo.",
  vampiro: "Cabo Eleitoral, acorde e troque as fichas antes da manchete.",
  amanhecer: "A cidade acordou. Agora todo mundo tem uma versão oficial.",
};

export const rioSatiraTheme: ThemePack = {
  schemaVersion: 1,
  id: "rio-satira",
  status: "preview",
  access: "premium",
  rights: {
    themeId: "rio-satira",
    status: "blocked",
    owner: "Igor Melo",
    provenanceDocument: "docs/legal/ASSET_PROVENANCE.md",
    legalOpinionDate: null,
    trademarkClearanceDate: null,
    storeClearanceDate: null,
    publishable: false,
  },
  name: "Rio: Arquivo da Madrugada",
  shortName: "Rio Sátira",
  locale: "pt-BR",
  brand: {
    title: "Rio: Arquivo da Madrugada",
    eyebrow: "ARQUIVO DA",
    name: "MADRUGADA",
    tagline: "Morro e asfalto · uma noite · versões demais",
    description: "Sátira de dedução social sobre poder, mídia e identidade política no Rio.",
    logoSrc: "/themes/rio-satira/art/logo.png",
    cardBackSrc: "/themes/rio-satira/art/card-back.png",
    shareText: "Tem pasta circulando no Arquivo da Madrugada!\nSala {code}: {url}",
  },
  terminology: {
    center: "Arquivo",
    centerPositionNames: ["pasta esquerda", "pasta central", "pasta direita"],
    village: "cidade",
    wolfPack: "esquema",
  },
  roles: {
    aldeao: {
      name: "Morador",
      letter: "M",
      description: "Só quer descobrir quem manda no esquema e trabalhar amanhã.",
      nightHint: "Feche os olhos. Amanhã cedo ainda tem cidade.",
      artSrc: "/themes/rio-satira/art/morador.png",
      artAlt: "Moradora cansada com contas em um corredor de prédio com vazamento",
    },
    lavrador: {
      name: "Motoboy",
      letter: "M",
      description: "Conhece todos os atalhos, mas nesta noite não abre nenhuma pasta.",
      nightHint: "Estacione a moto e espere a cidade acordar.",
      artSrc: "/themes/rio-satira/art/motoboy.png",
      artAlt: "Motoboy com capacete, celular e moto numa via iluminada à noite",
    },
    cacador: {
      name: "Olheiro",
      letter: "O",
      description: "Guarda uma pasta do Arquivo sem saber o que há dentro.",
      nightHint: "Escolha uma pasta para esconder sem abrir.",
      artSrc: "/themes/rio-satira/art/olheiro.png",
      artAlt: "Olheiro com binóculo e rádio sobre uma laje inacabada à noite",
    },
    bruxa: {
      name: "Tia do Zap",
      letter: "T",
      description: "Descobre a ficha de alguém e vê quais pastas sumiram, antes de encaminhar sem contexto.",
      nightHint: "Confira uma pessoa e conte as pastas no Arquivo.",
      artSrc: "/themes/rio-satira/art/tia-do-zap.png",
      artAlt: "Tia do Zap cercada por alertas enquanto encaminha mensagens na cozinha",
    },
    lobisomem: {
      name: "Miliciano",
      letter: "M",
      description: "Reconhece o esquema e consulta as pastas restantes apenas no seu turno.",
      nightHint: "Veja quem está no esquema e memorize o Arquivo.",
      artSrc: "/themes/rio-satira/art/miliciano.png",
      artAlt: "Miliciano fictício com molho de chaves e livro-caixa num escritório escuro",
    },
    mumia: {
      name: "Influencer",
      letter: "I",
      description: "Não age à noite e monetiza o cancelamento se receber os votos.",
      nightHint: "Prepare a retratação e espere a timeline acordar.",
      artSrc: "/themes/rio-satira/art/influencer.png",
      artAlt: "Influencer posando diante de um celular rachado e uma luz circular na laje",
    },
    esqueleto: {
      name: "Comentarista",
      letter: "C",
      description: "Não age à noite e vence se a cidade transformar opinião em sentença.",
      nightHint: "Guarde o palpite até o debate.",
      artSrc: "/themes/rio-satira/art/comentarista.png",
      artAlt: "Comentarista apontando para imagens de crime em um estúdio sensacionalista",
    },
    zumbi: {
      name: "Laranja",
      letter: "L",
      description: "Assume uma ficha do Arquivo e passa a agir como ela.",
      nightHint: "Escolha a ficha que vai ficar no seu nome.",
      artSrc: "/themes/rio-satira/art/laranja.png",
      artAlt: "Laranja apreensivo assinando papéis sob sombras e fitas vermelhas",
    },
    vampiro: {
      name: "Cabo Eleitoral",
      letter: "C",
      description: "Troca sua ficha com alguém ou com uma pasta do Arquivo em segredo.",
      nightHint: "Troque duas versões antes do fechamento da edição.",
      artSrc: "/themes/rio-satira/art/cabo-eleitoral.png",
      artAlt: "Cabo eleitoral ao telefone distribuindo envelopes numa sala de campanha fictícia",
    },
  },
  teams: {
    aliados: { name: "Cidade", goal: "Exponham pelo menos um Miliciano.", winBlurb: "A cidade abriu a pasta certa." },
    lobisomens: { name: "Esquema", goal: "Controlem a narrativa e sobrevivam ao voto.", winBlurb: "O esquema arquivou o caso." },
    "mortos-vivos": { name: "Cancelados", goal: "Façam o voto cair no Influencer ou no Comentarista.", winBlurb: "O cancelamento virou engajamento." },
    zumbi: { name: "Laranja", goal: "Assuma outra ficha; ela define sua vitória.", winBlurb: "A ficha mudou de dono." },
  },
  rulesCopy: {
    deckSummary: "O elenco mecânico não muda: três fichas sempre ficam no Arquivo.",
    intro: "Cada pessoa recebe uma ficha secreta e três pastas ficam no Arquivo.",
    voting: "Quando amanhecer, comparem versões e votem em quem controla a história.",
    winPriority: "Cancelados vencem se virarem o alvo; a Cidade vence ao expor o esquema ou pela pasta do Olheiro.",
  },
  narration: {
    ttsLocale: "pt-BR",
    segments: {
      intro: { narration: lines.intro },
      cacador: { narration: lines.cacador, actorPrompt: "Esconda uma pasta do Arquivo sem olhar." },
      bruxa: { narration: lines.bruxa, actorPrompt: "Veja uma ficha e observe o Arquivo." },
      lobisomem: { narration: lines.lobisomem, actorPrompt: "Reconheça o esquema e memorize o Arquivo." },
      zumbi: { narration: lines.zumbi, actorPrompt: "Assuma uma ficha e execute a ação dela." },
      vampiro: { narration: lines.vampiro, actorPrompt: "Troque sua ficha com alguém ou com o Arquivo." },
      amanhecer: { narration: lines.amanhecer },
    },
    subtitles: buildNarrationSubtitles(lines),
  },
  ambient: { audioSrc: "/audio/background.mp3", volume: 0.12 },
  palette: {
    background: "#071b2c", backgroundSoft: "#102f49", backgroundGlow: "#155b72",
    surface: "#123f5b", surfaceStrong: "#0b2232", primary: "#a52b3b",
    primaryStrong: "#d83c50", accent: "#f4bd3f", accentSoft: "#ffe083",
    text: "#f5f0dc", textMuted: "#b9c7c9", border: "#030b12",
    positive: "#3dbf8a", danger: "#e44b55",
  },
};
